name: Docker Image CI

on: [push, pull_request]

jobs:
    build:
        name: Package & Deploy
        runs-on: ubuntu-latest
        timeout-minutes: 25
        steps:
            - name: Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.6.0
              with:
                  access_token: ${{ github.token }}
                  
            - uses: actions/checkout@v2
            - name: Set up JDK 21
              uses: actions/setup-java@v1
              with:
                  java-version: '21'
                  
            - name: Build with Maven
              run: mvn -B package --file ./backend/pom.xml
              
            - name: Check Maven
              run: ls ./backend/target
            - name: LS
              name: ls .
              
            - name: Build the Docker images
              run: |
                docker build -t spring-docker ./.github/workflows/Backend
                docker build -t react-docker ./frontend

